#! /bin/bash

if [ "$#" -eq 0 ]; then
    docker run --rm -ti -v ${PWD}:/work dkarchmervue/moviepy ffmpeg -version
    exit 1
fi

docker run --rm -ti -v ${PWD}:/work dkarchmervue/moviepy ffmpeg $@

exit 0
