#! /bin/bash

# if [ "$#" -eq 0 ]; then
#     docker run --rm -ti -v ${PWD}:/work dkarchmervue/moviepy python -V
#     exit 1
# fi

docker run --rm -ti -v ${PWD}:/work dkarchmervue/moviepy python $@

exit 0

